name: AllAboard
main: com.vcazan.allaboard.AllAboard
version: 0.05
commands:
  autoboard:
    description: Turns AllAboard Boarding On/Off
    usage: |
           /<command>
           Example: /<command> | Turns AllAboard Boarding On/Off
          